version: '3.9'
services:
  backend:
    build: ./backend
    container_name: booksocial-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - cache
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      target: development
    container_name: booksocial-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: booksocial-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  cache:
    image: redis:7
    container_name: booksocial-cache
    ports:
      - "6379:6379"

volumes:
  db_data:
