# Generated by Django 5.2.17 on 2026-09-28 17:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('signup', 'Registro de Usuario'), ('login', 'Inicio de Sesión'), ('book_view', 'Visualización de Libro'), ('book_added', 'Libro Añadido a Biblioteca'), ('reading_started', 'Lectura Iniciada'), ('reading_finished', 'Lectura Finalizada'), ('review_created', 'Reseña Creada'), ('follow_created', 'Usuario Seguido'), ('list_created', 'Lista Creada'), ('message_sent', 'Mensaje Enviado'), ('recommendation_shown', 'Recomendación Mostrada'), ('recommendation_clicked', 'Recomendación Clickeada'), ('recommendation_dismissed', 'Recomendación Descartada')], db_index=True, max_length=40, verbose_name='Tipo de evento')),
                ('session_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Identificador disociado de sesión')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos cuantitativos contextuales')),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='Hash criptográfico disociado de IP (sin PII)')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha y hora del evento')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL, verbose_name='Usuario (si está autenticado)')),
            ],
            options={
                'verbose_name': 'Evento de Analítica de Producto',
                'verbose_name_plural': 'Eventos de Analítica de Producto',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='idx_pae_type_time'), models.Index(fields=['user', 'timestamp'], name='idx_pae_user_time'), models.Index(fields=['session_id', 'timestamp'], name='idx_pae_sess_time')],
            },
        ),
    ]
