# Generated by Django 5.2.17 on 2026-09-28 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bug', 'Bug'), ('confusing_ux', 'Confusing UX'), ('missing_feature', 'Missing Feature'), ('performance', 'Performance'), ('privacy_concern', 'Privacy Concern'), ('recommendation_quality', 'Recommendation Quality'), ('general_feedback', 'General Feedback')], db_index=True, default='general_feedback', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('page_url', models.CharField(blank=True, default='', max_length=500)),
                ('device_info', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beta_feedback_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beta Feedback',
                'verbose_name_plural': 'Beta Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BetaInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('invited_email', models.EmailField(blank=True, default='', max_length=254)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_beta_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beta Invitation',
                'verbose_name_plural': 'Beta Invitations',
                'ordering': ['-created_at'],
            },
        ),
    ]
