# Generated by Django 5.2.17 on 2026-09-12 11:00

import mybookconnect.media_security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0002_message_idx_msg_conv_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen del chat (JPEG, PNG, WebP; máx 10MB; dimensiones 50x50 a 6000x6000px)', null=True, upload_to='chat_images/', validators=[mybookconnect.media_security.ChatImageValidator()]),
        ),
    ]
