# Generated by Django 5.2.17 on 2026-09-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0003_alter_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_moderated',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica si el mensaje ha sido ocultado por moderación'),
        ),
    ]
