# Generated by Django 5.2.17 on 2026-09-13 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0004_message_is_moderated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica. Si es null, el registro está activo.', null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'deleted_at'], name='idx_msg_conv_del'),
        ),
    ]
