# Generated by Django 5.2.17 on 2026-09-24 06:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=64, verbose_name='ID de petición')),
                ('provider', models.CharField(db_index=True, max_length=64, verbose_name='Proveedor de IA')),
                ('model', models.CharField(max_length=128, verbose_name='Modelo utilizado')),
                ('prompt_tokens', models.PositiveIntegerField(default=0, verbose_name='Tokens de entrada (Prompt)')),
                ('completion_tokens', models.PositiveIntegerField(default=0, verbose_name='Tokens de salida (Respuesta)')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='Tokens totales')),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10, verbose_name='Coste estimado (USD)')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='Duración (milisegundos)')),
                ('success', models.BooleanField(default=True, verbose_name='Llamada exitosa')),
                ('error', models.TextField(blank=True, default='', verbose_name='Detalle de error si falló')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario solicitante')),
            ],
            options={
                'verbose_name': 'Registro de uso de IA',
                'verbose_name_plural': 'Registros de uso de IA',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='idx_ai_user_created'), models.Index(fields=['provider', 'created_at'], name='idx_ai_prov_created')],
            },
        ),
    ]
