# Generated by Django 5.0 on 2025-10-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author_photo_book_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='enrichment_attempted',
            field=models.BooleanField(default=False),
        ),
    ]
