# Generated by Django 5.0 on 2025-10-17 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_author_enrichment_attempted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userbook',
            index=models.Index(fields=['user', '-updated_at'], name='books_userb_user_id_64d5dc_idx'),
        ),
        migrations.AddIndex(
            model_name='userbook',
            index=models.Index(fields=['user', 'book'], name='books_userb_user_id_fa917a_idx'),
        ),
        migrations.AddIndex(
            model_name='userbook',
            index=models.Index(fields=['user', 'is_read'], name='books_userb_user_id_911f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='userbook',
            index=models.Index(fields=['user', 'wishlist'], name='books_userb_user_id_c5e3a5_idx'),
        ),
    ]
