# Generated by Django 5.0 on 2025-11-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    # Sustituye el 0003 duplicado de la otra rama si ya estaba aplicado.
    replaces = [
        ('books', '0003_category_book_categories'),
    ]

    dependencies = [
        ('books', '0005_errata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.category'),
        ),
    ]
