# Generated by Django 5.2.17 on 2026-09-09 06:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_category_book_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='enrichment_attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
