# Generated by Django 5.2.17 on 2026-09-09 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_review_title_review_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('terms', 'Términos del Servicio'), ('privacy', 'Política de Privacidad'), ('cookies', 'Política de Cookies'), ('legal_notice', 'Aviso Legal')], unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Contenido en Markdown o HTML')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_legal_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
