# Generated by Django 5.2.17 on 2026-09-10 07:05

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_legaldocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='google_volume_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='openlibrary_edition_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='openlibrary_work_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userbook',
            name='current_page',
            field=models.PositiveIntegerField(default=0, help_text='Página actual de lectura'),
        ),
        migrations.AddField(
            model_name='userbook',
            name='finished_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbook',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, help_text='Porcentaje de lectura de 0 a 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='userbook',
            name='started_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbook',
            name='status',
            field=models.CharField(choices=[('want_to_read', 'Quiero leer'), ('reading', 'Leyendo'), ('read', 'Leído'), ('abandoned', 'Abandonado')], db_index=True, default='want_to_read', max_length=20),
        ),
        migrations.AddIndex(
            model_name='userbook',
            index=models.Index(fields=['user', 'status'], name='books_userb_user_id_f00db1_idx'),
        ),
    ]
