# Generated by Django 5.2.17 on 2026-09-10 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_google_volume_id_book_openlibrary_edition_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='errata',
            name='books_errat_status_e829db_idx',
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='idx_book_title'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title', 'author'], name='idx_book_title_author'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-created_at'], name='idx_book_created_at'),
        ),
        migrations.AddIndex(
            model_name='errata',
            index=models.Index(fields=['status', '-created_at'], name='idx_errata_status_created'),
        ),
        migrations.AddIndex(
            model_name='errata',
            index=models.Index(fields=['book', 'status'], name='idx_errata_book_status'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['book', '-created_at'], name='idx_review_book_created'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', '-created_at'], name='idx_review_user_created'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='idx_review_created_at'),
        ),
        migrations.AddIndex(
            model_name='userbook',
            index=models.Index(fields=['is_read', '-updated_at'], name='idx_userbook_read_updated'),
        ),
        migrations.AddIndex(
            model_name='userbook',
            index=models.Index(fields=['status', '-updated_at'], name='idx_userbook_status_updated'),
        ),
    ]
