# Generated by Django 5.2.17 on 2026-09-11 07:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_reviewcomment_reviewlike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('description', models.TextField(blank=True, default='')),
                ('privacy', models.CharField(choices=[('public', 'Pública'), ('followers', 'Solo seguidores'), ('private', 'Privada')], db_index=True, default='public', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingListFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reading_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='books.readinglist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_reading_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_list_items', to='books.book')),
                ('reading_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='books.readinglist')),
            ],
            options={
                'ordering': ['position', 'added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='readinglist',
            index=models.Index(fields=['user', '-updated_at'], name='idx_readinglist_user_updated'),
        ),
        migrations.AddIndex(
            model_name='readinglist',
            index=models.Index(fields=['privacy', '-updated_at'], name='idx_readinglist_priv_updated'),
        ),
        migrations.AddConstraint(
            model_name='readinglist',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_user_reading_list_slug'),
        ),
        migrations.AddIndex(
            model_name='readinglistfollow',
            index=models.Index(fields=['user', '-created_at'], name='idx_readinglistfollow_user'),
        ),
        migrations.AddConstraint(
            model_name='readinglistfollow',
            constraint=models.UniqueConstraint(fields=('user', 'reading_list'), name='unique_reading_list_follow'),
        ),
        migrations.AddIndex(
            model_name='readinglistitem',
            index=models.Index(fields=['reading_list', 'position'], name='idx_readinglistitem_pos'),
        ),
        migrations.AddConstraint(
            model_name='readinglistitem',
            constraint=models.UniqueConstraint(fields=('reading_list', 'book'), name='unique_reading_list_book'),
        ),
    ]
