# Generated by Django 5.2.17 on 2026-09-11 11:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_readinglist_readinglistfollow_readinglistitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('action', models.CharField(choices=[('recommendation_shown', 'Recomendación mostrada'), ('recommendation_clicked', 'Recomendación clickeada'), ('book_opened', 'Libro abierto'), ('wishlist_added', 'Añadido a lista de deseos'), ('reading_started', 'Lectura iniciada'), ('reading_finished', 'Lectura finalizada'), ('rated', 'Valorado')], db_index=True, max_length=30)),
                ('strategy', models.CharField(blank=True, db_index=True, default='hybrid', max_length=50)),
                ('algorithm_version', models.CharField(db_index=True, default='v1.0', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedbacks', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action', '-created_at'], name='idx_recfb_user_act_date'), models.Index(fields=['book', 'action'], name='idx_recfb_book_act'), models.Index(fields=['algorithm_version', 'action'], name='idx_recfb_algo_act'), models.Index(fields=['strategy', 'action'], name='idx_recfb_strat_act')],
            },
        ),
    ]
