# Generated by Django 5.2.17 on 2026-09-12 11:00

import mybookconnect.media_security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_recommendationfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, help_text='Fotografía del autor (JPEG, PNG, WebP; máx 5MB; dimensiones 50x50 a 6000x6000px)', null=True, upload_to='author_photos/', validators=[mybookconnect.media_security.AuthorPhotoImageValidator()]),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, help_text='Portada del libro (JPEG, PNG, WebP; máx 10MB; dimensiones 50x50 a 6000x6000px)', null=True, upload_to='covers/', validators=[mybookconnect.media_security.CoverImageValidator()]),
        ),
    ]
