# Generated by Django 5.2.17 on 2026-09-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_author_photo_alter_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_moderated',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica si la reseña ha sido ocultada por moderación'),
        ),
    ]
