# Generated by Django 5.2.17 on 2026-09-13 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_review_is_moderated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review_user_book',
        ),
        migrations.AddField(
            model_name='review',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica. Si es null, el registro está activo.', null=True),
        ),
        migrations.AlterField(
            model_name='errata',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_erratas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewcomment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica. Si es null, el registro está activo.', null=True),
        ),
        migrations.AddIndex(
            model_name='errata',
            index=models.Index(fields=['author', 'status'], name='idx_errata_author_status'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['book', 'deleted_at'], name='idx_review_book_del'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'deleted_at'], name='idx_review_user_del'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'book'), name='unique_active_review_user_book'),
        ),
    ]
