# Generated by Django 5.2.17 on 2026-09-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_remove_review_unique_review_user_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Vector de embedding semántico de la obra', null=True),
        ),
    ]
