# Generated by Django 5.2.17 on 2026-09-21 08:30

import django.core.validators
from django.conf import settings
from django.db import migrations, models


def rescale_ratings_to_1_to_5(apps, schema_editor):
    Review = apps.get_model('books', 'Review')
    UserBook = apps.get_model('books', 'UserBook')
    Book = apps.get_model('books', 'Book')

    # Re-escalar reviews con rating > 5
    for rev in Review.objects.filter(rating__gt=5):
        # Mapeo proporcional entero: 10->5, 9->5, 8->4, 7->4, 6->3
        rev.rating = max(1, min(5, (rev.rating + 1) // 2))
        rev.save(update_fields=['rating'])

    # Re-escalar userbooks con rating > 5
    for ub in UserBook.objects.filter(rating__gt=5):
        ub.rating = max(1, min(5, (ub.rating + 1) // 2))
        ub.save(update_fields=['rating'])

    # Recalcular average_rating en libros afectados
    for book in Book.objects.all():
        active_reviews = Review.objects.filter(book=book, deleted_at__isnull=True)
        count = active_reviews.count()
        if count > 0:
            avg = sum(r.rating for r in active_reviews) / count
            book.average_rating = round(avg, 2)
            book.save(update_fields=['average_rating'])


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_badge_readingchallenge_readingstreak_dailyreadinglog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbook',
            unique_together=set(),
        ),
        migrations.RunPython(rescale_ratings_to_1_to_5, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(help_text='Calificación pública de 1 a 5 estrellas.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Calificación personal privada de 1 a 5 estrellas.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='check_review_rating_range_1_to_5'),
        ),
        migrations.AddConstraint(
            model_name='userbook',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='unique_user_book'),
        ),
        migrations.AddConstraint(
            model_name='userbook',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rating__gte', 1), ('rating__lte', 5)), ('rating__isnull', True), _connector='OR'), name='check_userbook_rating_range_1_to_5'),
        ),
    ]
