# Generated by Django 5.2.17 on 2026-09-24 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_rating_1_to_5_and_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField(blank=True, default=list, verbose_name='Vector de embedding')),
                ('dimension', models.PositiveIntegerField(default=768, verbose_name='Dimensión del vector')),
                ('embedding_model', models.CharField(default='nomic-embed-text', max_length=128, verbose_name='Modelo generador')),
                ('embedding_version', models.CharField(default='v1.0', max_length=32, verbose_name='Versión del pipeline')),
                ('embedded_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de vectorización')),
                ('embedding_status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido'), ('stale', 'Desactualizado')], db_index=True, default='pending', max_length=20, verbose_name='Estado del embedding')),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Hash SHA256 del contenido fuente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_record', to='books.book', verbose_name='Libro asociado')),
            ],
            options={
                'verbose_name': 'Embedding de Libro',
                'verbose_name_plural': 'Embeddings de Libros',
                'indexes': [models.Index(fields=['embedding_status', 'embedded_at'], name='idx_emb_status_date'), models.Index(fields=['embedding_model', 'embedding_version'], name='idx_emb_mod_ver')],
            },
        ),
    ]
