# Generated by Django 5.2.17 on 2026-09-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_bookembedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationfeedback',
            name='action',
            field=models.CharField(choices=[('recommendation_shown', 'Recomendación mostrada'), ('recommendation_clicked', 'Recomendación clickeada'), ('book_opened', 'Libro abierto'), ('wishlist_added', 'Añadido a lista de deseos'), ('reading_started', 'Lectura iniciada'), ('reading_finished', 'Lectura finalizada'), ('rated', 'Valorado'), ('dismissed', 'Descartado')], db_index=True, max_length=30),
        ),
    ]
