# Generated by Django 5.2.17 on 2026-09-26 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_recommendationfeedback_dismissed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author', '-created_at'], name='idx_book_author_created'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['book', 'rating'], name='idx_review_book_rating'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'book'], name='idx_review_user_book'),
        ),
        migrations.AddIndex(
            model_name='userbook',
            index=models.Index(fields=['book', 'status'], name='idx_userbook_book_status'),
        ),
    ]
