# Generated by Django 5.2.17 on 2026-09-27 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_book_idx_book_author_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglist',
            name='is_moderated',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica si la lista ha sido ocultada por el equipo de moderación'),
        ),
        migrations.AddIndex(
            model_name='readinglist',
            index=models.Index(fields=['is_moderated', '-updated_at'], name='idx_readinglist_mod_updated'),
        ),
    ]
