# Generated by Django 5.2.17 on 2026-09-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_readinglist_is_moderated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='slug',
            field=models.SlugField(choices=[('terms', 'Términos del Servicio'), ('privacy', 'Política de Privacidad'), ('cookies', 'Política de Cookies'), ('legal_notice', 'Aviso Legal'), ('content_policy', 'Política de Contenido'), ('deletion_policy', 'Política de Eliminación y Retención'), ('contact', 'Contacto y Soporte Legal')], unique=True),
        ),
    ]
