# Generated by Django 5.2.17 on 2026-09-27 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_alter_legaldocument_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglist',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='Número de veces que la lista ha sido abierta/consultada'),
        ),
        migrations.CreateModel(
            name='ReadingListComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica. Si es null, el registro está activo.', null=True)),
                ('content', models.TextField(help_text='Contenido del comentario sobre la lista')),
                ('is_moderated', models.BooleanField(db_index=True, default=False, help_text='Indica si el comentario ha sido ocultado por el equipo de moderación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='books.readinglist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_list_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['reading_list', 'created_at'], name='idx_rlcomment_list_created'), models.Index(fields=['reading_list', 'deleted_at'], name='idx_rlcomment_list_del')],
            },
        ),
    ]
