# Generated by Django 5.2.17 on 2026-09-29 17:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_readinglist_views_count_readinglistcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('paperback', 'Libro Físico'), ('ebook', 'Ebook Kindle'), ('audiobook', 'Audiolibro Audible')], db_index=True, default='paperback', max_length=20, verbose_name='Formato de compra')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha del clic')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_clicks', to='books.book', verbose_name='Libro consultado')),
            ],
            options={
                'verbose_name': 'Clic de Afiliado',
                'verbose_name_plural': 'Clics de Afiliados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pen_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre de pluma / artístico')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía profesional')),
                ('website', models.URLField(blank=True, verbose_name='Sitio web oficial')),
                ('twitter', models.CharField(blank=True, max_length=100, verbose_name='Usuario de Twitter/X')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Usuario de Instagram')),
                ('is_verified', models.BooleanField(db_index=True, default=False, verbose_name='Autor verificado')),
                ('verification_notes', models.TextField(blank=True, verbose_name='Notas de verificación o pruebas de autoría')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('author', models.ForeignKey(blank=True, help_text='Registro del catálogo de autores reclamado y verificado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='books.author', verbose_name='Autor del catálogo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author_profile', to=settings.AUTH_USER_MODEL, verbose_name='Cuenta de usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Autor',
                'verbose_name_plural': 'Perfiles de Autores',
            },
        ),
        migrations.CreateModel(
            name='AuthorAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del comunicado')),
                ('content', models.TextField(verbose_name='Contenido del comunicado')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Fijado en el perfil')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_announcements', to='books.book', verbose_name='Libro relacionado')),
                ('author_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='books.authorprofile', verbose_name='Perfil de autor')),
            ],
            options={
                'verbose_name': 'Comunicado de Autor',
                'verbose_name_plural': 'Comunicados de Autores',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
