# Generated by Django 5.2.17 on 2026-09-29 17:32

from django.db import migrations, models


def populate_book_authors(apps, schema_editor):
    Book = apps.get_model('books', 'Book')
    for book in Book.objects.filter(author__isnull=False).iterator():
        book.authors.add(book.author)


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0028_affiliateclick_authorprofile_authorannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='all_books', to='books.author'),
        ),
        migrations.RunPython(populate_book_authors, reverse_code=migrations.RunPython.noop),
    ]
