# Generated by Django 5.2.17 on 2026-10-01 16:52

import mybookconnect.media_security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0029_book_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, help_text='Fotografía o imagen adjunta a la reseña (ej. portada, dedicatoria, pasaje; máx 10MB)', null=True, upload_to='reviews/', validators=[mybookconnect.media_security.CoverImageValidator()]),
        ),
    ]
