# Generated by Django 5.2.17 on 2026-10-02 17:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0030_review_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Pregunta')),
                ('answer', models.TextField(verbose_name='Respuesta')),
                ('category', models.CharField(choices=[('general', 'General'), ('authors', 'Autores y Verificación'), ('books', 'Libros y Biblioteca'), ('account', 'Cuenta y Privacidad'), ('community', 'Comunidad y Red Social')], db_index=True, default='general', max_length=50, verbose_name='Categoría temática')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Orden')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Publicada')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Pregunta Frecuente (FAQ)',
                'verbose_name_plural': 'Preguntas Frecuentes (FAQs)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='author',
            name='aliases',
            field=models.JSONField(blank=True, default=list, verbose_name='Alias y variantes de nombre'),
        ),
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='author',
            name='canonical_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre canónico'),
        ),
        migrations.AddField(
            model_name='author',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_authors', to=settings.AUTH_USER_MODEL, verbose_name='Usuario propietario verificado'),
        ),
        migrations.AddField(
            model_name='author',
            name='death_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fallecimiento'),
        ),
        migrations.AddField(
            model_name='author',
            name='external_ids',
            field=models.JSONField(blank=True, default=dict, verbose_name='Identificadores externos'),
        ),
        migrations.AddField(
            model_name='author',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario de Instagram'),
        ),
        migrations.AddField(
            model_name='author',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Autor verificado'),
        ),
        migrations.AddField(
            model_name='author',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidad / Origen'),
        ),
        migrations.AddField(
            model_name='author',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario de Twitter/X'),
        ),
        migrations.AddField(
            model_name='author',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio web oficial'),
        ),
        migrations.AddField(
            model_name='author',
            name='wikipedia_url',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace a Wikipedia'),
        ),
        migrations.CreateModel(
            name='AuthorClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada')], db_index=True, default='pending', max_length=20, verbose_name='Estado de la solicitud')),
                ('proof_description', models.TextField(help_text='Indica cómo contrastar tu autoría (web oficial, editorial, ISBN, etc.)', verbose_name='Descripción de autoría o acreditación de identidad')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto profesional')),
                ('supporting_link', models.URLField(blank=True, null=True, verbose_name='Enlace de respaldo oficial')),
                ('moderation_notes', models.TextField(blank=True, verbose_name='Notas de moderación interna')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de solicitud')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='books.author', verbose_name='Autor del catálogo')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_author_claims', to=settings.AUTH_USER_MODEL, verbose_name='Moderador asignado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_claims', to=settings.AUTH_USER_MODEL, verbose_name='Usuario solicitante')),
            ],
            options={
                'verbose_name': 'Reclamación de Autor',
                'verbose_name_plural': 'Reclamaciones de Autores',
                'ordering': ['-created_at'],
            },
        ),
    ]
