# Generated by Django 5.2.17 on 2026-10-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0031_faq_author_aliases_author_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='additional_isbns',
            field=models.JSONField(blank=True, default=list, help_text='Listado de ISBNs adicionales o de otras ediciones (físico, digital, etc.)'),
        ),
    ]
