# Generated by Django 5.2.17 on 2026-10-05 07:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0032_book_additional_isbns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del club')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug URL')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='club_covers/', verbose_name='Imagen de portada')),
                ('is_private', models.BooleanField(db_index=True, default=False, verbose_name='Club privado (requiere aprobación)')),
                ('rules', models.TextField(blank=True, verbose_name='Reglas de convivencia')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_clubs', to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
                ('current_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_clubs', to='books.book', verbose_name='Lectura actual')),
            ],
            options={
                'verbose_name': 'Club de Lectura',
                'verbose_name_plural': 'Clubs de Lectura',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingClubBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CURRENT', 'Lectura Actual'), ('UPCOMING', 'Próxima Lectura'), ('FINISHED', 'Lectura Finalizada')], db_index=True, default='UPCOMING', max_length=20, verbose_name='Estado de lectura')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha estimada de fin')),
                ('target_milestones', models.CharField(blank=True, max_length=255, verbose_name='Hitos o metas de capítulos (ej. Capítulos 1 al 10 para semana 1)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Añadido el')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_readings', to='books.book', verbose_name='Libro')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_plan', to='books.readingclub', verbose_name='Club')),
            ],
            options={
                'verbose_name': 'Lectura de Club',
                'verbose_name_plural': 'Lecturas de Clubs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingClubDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título del debate')),
                ('content', models.TextField(verbose_name='Contenido o pregunta inicial')),
                ('is_pinned', models.BooleanField(db_index=True, default=False, verbose_name='Fijado en la parte superior')),
                ('has_spoilers', models.BooleanField(default=False, verbose_name='Contiene spoilers')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_discussions', to=settings.AUTH_USER_MODEL, verbose_name='Autor del debate')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_discussions', to='books.book', verbose_name='Libro vinculado')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='books.readingclub', verbose_name='Club')),
            ],
            options={
                'verbose_name': 'Debate de Club',
                'verbose_name_plural': 'Debates de Clubs',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingClubDiscussionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Comentario')),
                ('has_spoilers', models.BooleanField(default=False, verbose_name='Contiene spoilers')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_discussion_comments', to=settings.AUTH_USER_MODEL, verbose_name='Autor del comentario')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='books.readingclubdiscussion', verbose_name='Debate')),
            ],
            options={
                'verbose_name': 'Comentario de Debate',
                'verbose_name_plural': 'Comentarios de Debates',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('MODERATOR', 'Moderador'), ('MEMBER', 'Miembro')], default='MEMBER', max_length=20, verbose_name='Rol en el club')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('PENDING', 'Pendiente de aprobación'), ('BANNED', 'Bloqueado')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Estado de membresía')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='books.readingclub', verbose_name='Club de lectura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuario miembro')),
            ],
            options={
                'verbose_name': 'Miembro de Club',
                'verbose_name_plural': 'Miembros de Clubs',
                'ordering': ['-joined_at'],
                'unique_together': {('club', 'user')},
            },
        ),
    ]
