# Generated by Django 5.2.17 on 2026-10-05 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0033_readingclub_readingclubbook_readingclubdiscussion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingListCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('EDITOR', 'Editor'), ('VIEWER', 'Lector')], default='EDITOR', max_length=20, verbose_name='Rol de colaboración')),
                ('status', models.CharField(choices=[('PENDING', 'Invitación pendiente'), ('ACCEPTED', 'Aceptada'), ('REJECTED', 'Rechazada')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado de la invitación')),
                ('can_add_books', models.BooleanField(default=True, verbose_name='Puede añadir libros')),
                ('can_remove_books', models.BooleanField(default=False, verbose_name='Puede eliminar libros de otros')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de invitación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Colaborador de Lista',
                'verbose_name_plural': 'Colaboradores de Listas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='readinglist',
            name='is_collaborative',
            field=models.BooleanField(db_index=True, default=False, help_text='Permite que otros usuarios invitados colaboren añadiendo y organizando libros', verbose_name='Lista colaborativa'),
        ),
        migrations.AddField(
            model_name='readinglistitem',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que aportó este libro a la lista (dueño o colaborador)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_reading_list_items', to=settings.AUTH_USER_MODEL, verbose_name='Añadido por'),
        ),
        migrations.AddIndex(
            model_name='readinglist',
            index=models.Index(fields=['is_collaborative', '-updated_at'], name='idx_readinglist_collab_updated'),
        ),
        migrations.AddField(
            model_name='readinglistcollaborator',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_collaborations', to=settings.AUTH_USER_MODEL, verbose_name='Invitado por'),
        ),
        migrations.AddField(
            model_name='readinglistcollaborator',
            name='reading_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='books.readinglist', verbose_name='Lista de lectura'),
        ),
        migrations.AddField(
            model_name='readinglistcollaborator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to=settings.AUTH_USER_MODEL, verbose_name='Usuario colaborador'),
        ),
        migrations.AlterUniqueTogether(
            name='readinglistcollaborator',
            unique_together={('reading_list', 'user')},
        ),
    ]
