# Generated by Django 5.2.17 on 2026-10-05 20:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0034_readinglistcollaborator_readinglist_is_collaborative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título del evento')),
                ('description', models.TextField(verbose_name='Descripción del evento')),
                ('event_type', models.CharField(choices=[('BOOK_LAUNCH', 'Lanzamiento / Presentación'), ('SIGNING', 'Firma de ejemplares'), ('QA_SESSION', 'Sesión de preguntas (Q&A)'), ('READING', 'Lectura pública'), ('WORKSHOP', 'Taller literario'), ('OTHER', 'Otro evento')], default='BOOK_LAUNCH', max_length=30, verbose_name='Tipo de evento')),
                ('event_format', models.CharField(choices=[('ONLINE', 'Virtual / En línea'), ('IN_PERSON', 'Presencial'), ('HYBRID', 'Híbrido')], default='ONLINE', max_length=20, verbose_name='Formato')),
                ('start_time', models.DateTimeField(db_index=True, verbose_name='Fecha y hora de inicio')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de fin')),
                ('event_timezone', models.CharField(default='Europe/Madrid', max_length=50, verbose_name='Zona horaria')),
                ('location_name', models.CharField(blank=True, max_length=255, verbose_name='Lugar o plataforma (ej. Librería Alberti / Zoom)')),
                ('location_address', models.CharField(blank=True, max_length=255, verbose_name='Dirección física')),
                ('online_url', models.URLField(blank=True, max_length=500, verbose_name='Enlace virtual o streaming')),
                ('max_attendees', models.PositiveIntegerField(blank=True, null=True, verbose_name='Aforo máximo')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Cancelado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='books.author', verbose_name='Autor')),
                ('author_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='books.authorprofile', verbose_name='Perfil oficial del autor')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_events', to='books.book', verbose_name='Libro relacionado')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_author_events', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Evento de Autor',
                'verbose_name_plural': 'Eventos de Autores',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='AuthorEventAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'Inscrito'), ('WAITLIST', 'Lista de espera'), ('CANCELLED', 'Cancelado')], db_index=True, default='REGISTERED', max_length=20, verbose_name='Estado de inscripción')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='Pregunta para el autor o nota adicional')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='books.authorevent', verbose_name='Evento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_event_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Usuario asistente')),
            ],
            options={
                'verbose_name': 'Asistente a Evento',
                'verbose_name_plural': 'Asistentes a Eventos',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'user'), name='unique_event_user_attendance')],
            },
        ),
    ]
