# Generated by Django 5.2.17 on 2026-10-07 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0035_authorevent_authoreventattendee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorannouncement',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': 'Publicación de Autor', 'verbose_name_plural': 'Publicaciones de Autores'},
        ),
        migrations.AddField(
            model_name='authorannouncement',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='books.author', verbose_name='Autor del catálogo'),
        ),
        migrations.AddField(
            model_name='authorannouncement',
            name='estimated_reading_time',
            field=models.PositiveIntegerField(default=1, verbose_name='Minutos estimados de lectura'),
        ),
        migrations.AddField(
            model_name='authorannouncement',
            name='excerpt',
            field=models.CharField(blank=True, max_length=500, verbose_name='Extracto / Resumen previo'),
        ),
        migrations.AddField(
            model_name='authorannouncement',
            name='has_spoilers',
            field=models.BooleanField(default=False, verbose_name='Contiene spoilers'),
        ),
        migrations.AddField(
            model_name='authorannouncement',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Es borrador'),
        ),
        migrations.AddField(
            model_name='authorannouncement',
            name='publication_type',
            field=models.CharField(choices=[('ANNOUNCEMENT', 'Comunicado oficial'), ('CHAPTER_PREVIEW', 'Adelanto de capítulo'), ('AUTHOR_DIARY', 'Diario de escritura'), ('DELETED_SCENE', 'Escena eliminada / Extra'), ('Q_AND_A', 'Preguntas y Respuestas')], default='ANNOUNCEMENT', max_length=30, verbose_name='Tipo de publicación'),
        ),
        migrations.AddField(
            model_name='authorannouncement',
            name='spoiler_warning',
            field=models.CharField(blank=True, max_length=255, verbose_name='Aviso de spoiler'),
        ),
        migrations.AddField(
            model_name='authorannouncement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='authorannouncement',
            name='content',
            field=models.TextField(verbose_name='Contenido completo'),
        ),
        migrations.AlterField(
            model_name='authorannouncement',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título de la publicación'),
        ),
    ]
