# Generated by Django 5.2.17 on 2026-10-07 07:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0036_alter_authorannouncement_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título del boletín')),
                ('description', models.TextField(blank=True, verbose_name='Descripción del boletín')),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Semanal'), ('BIWEEKLY', 'Quincenal'), ('MONTHLY', 'Mensual'), ('OCCASIONAL', 'Ocasional')], default='MONTHLY', max_length=20, verbose_name='Frecuencia estimada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Boletín activo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='books.author', verbose_name='Autor del catálogo')),
                ('author_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletters', to='books.authorprofile', verbose_name='Perfil oficial del autor')),
            ],
            options={
                'verbose_name': 'Boletín de Autor',
                'verbose_name_plural': 'Boletines de Autores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthorNewsletterIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título de la entrega')),
                ('subject', models.CharField(max_length=255, verbose_name='Asunto / Cabecera')),
                ('content', models.TextField(verbose_name='Contenido del boletín')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SCHEDULED', 'Programado'), ('SENT', 'Enviado')], db_index=True, default='DRAFT', max_length=20, verbose_name='Estado')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Fecha programada')),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de envío')),
                ('recipients_count', models.PositiveIntegerField(default=0, verbose_name='Destinatarios alcanzados')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Aperturas registradas')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='books.authornewsletter', verbose_name='Boletín')),
            ],
            options={
                'verbose_name': 'Entrega de Boletín',
                'verbose_name_plural': 'Entregas de Boletines',
                'ordering': ['-sent_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthorNewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Suscripción activa')),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de cancelación')),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de suscripción')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='books.authornewsletter', verbose_name='Boletín')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_newsletter_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Lector suscriptor')),
            ],
            options={
                'verbose_name': 'Suscriptor de Boletín',
                'verbose_name_plural': 'Suscriptores de Boletines',
                'ordering': ['-subscribed_at'],
                'constraints': [models.UniqueConstraint(fields=('newsletter', 'user'), name='unique_newsletter_user_subscription')],
            },
        ),
    ]
