# Generated by Django 5.2.17 on 2026-10-08 08:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0037_authornewsletter_authornewsletterissue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudiobookTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título de la pista / Capítulo')),
                ('track_number', models.PositiveIntegerField(default=1, verbose_name='Número de pista')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audiobooks/', verbose_name='Archivo de audio')),
                ('audio_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL externa o CDN del audio')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Duración en segundos')),
                ('narrator_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Nombre del narrador/a')),
                ('is_sample', models.BooleanField(db_index=True, default=False, verbose_name='¿Es muestra gratuita / preview pública?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de subida')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_tracks', to='books.book', verbose_name='Libro asociado')),
            ],
            options={
                'verbose_name': 'Pista de Audiolibro',
                'verbose_name_plural': 'Pistas de Audiolibros',
                'ordering': ['book', 'track_number'],
            },
        ),
        migrations.CreateModel(
            name='UserAudiobookProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_seconds', models.PositiveIntegerField(default=0, verbose_name='Posición actual de escucha en segundos')),
                ('playback_speed', models.FloatField(default=1.0, verbose_name='Velocidad de reproducción preferida')),
                ('is_completed', models.BooleanField(db_index=True, default=False, verbose_name='¿Audiolibro completado?')),
                ('last_listened_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Última sesión de escucha')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiobook_user_progress', to='books.book', verbose_name='Libro')),
                ('current_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_progress', to='books.audiobooktrack', verbose_name='Pista actual')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiobook_progress', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Progreso de Audiolibro',
                'verbose_name_plural': 'Progresos de Audiolibros',
                'ordering': ['-last_listened_at'],
            },
        ),
        migrations.AddIndex(
            model_name='audiobooktrack',
            index=models.Index(fields=['book', 'track_number'], name='idx_audio_book_track'),
        ),
        migrations.AddIndex(
            model_name='audiobooktrack',
            index=models.Index(fields=['is_sample'], name='idx_audio_is_sample'),
        ),
        migrations.AddIndex(
            model_name='useraudiobookprogress',
            index=models.Index(fields=['user', '-last_listened_at'], name='idx_audio_user_last_listen'),
        ),
        migrations.AlterUniqueTogether(
            name='useraudiobookprogress',
            unique_together={('user', 'book')},
        ),
    ]
