# Generated by Django 5.2.17 on 2026-10-08 20:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0038_audiobooktrack_useraudiobookprogress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookBuyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=100, verbose_name='Nombre de la librería o plataforma')),
                ('merchant_type', models.CharField(choices=[('indie_network', 'Red de Librerías Independientes (TodosTusLibros)'), ('online_retailer', 'Librería Online / Gran Cadena (Casa del Libro, Fnac, Amazon)'), ('publisher_direct', 'Editorial Directa / Web del Autor'), ('ebook_store', 'Tienda Digital (Kindle, Kobo, Google Play)'), ('audio_store', 'Plataforma de Audio (Audible, Storytel)')], db_index=True, default='online_retailer', max_length=30, verbose_name='Tipo de comercio')),
                ('format', models.CharField(choices=[('paperback', 'Tapa Blanda / Bolsillo'), ('hardcover', 'Tapa Dura'), ('ebook', 'Ebook / Digital'), ('audiobook', 'Audiolibro')], db_index=True, default='paperback', max_length=20, verbose_name='Formato del libro')),
                ('url', models.URLField(max_length=1000, verbose_name='Enlace directo a la tienda')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Precio estimado')),
                ('currency', models.CharField(default='EUR', max_length=10, verbose_name='Moneda')),
                ('is_official', models.BooleanField(db_index=True, default=False, verbose_name='Enlace oficial verificado por autor o editorial')),
                ('is_affiliate', models.BooleanField(default=False, verbose_name='Enlace con comisión de afiliación')),
                ('affiliate_tag', models.CharField(blank=True, default='', max_length=100, verbose_name='Etiqueta de afiliado')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Oferta activa')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_links', to='books.book', verbose_name='Libro asociado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_buy_links', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Enlace de Compra',
                'verbose_name_plural': 'Enlaces de Compra',
                'ordering': ['-is_official', 'merchant_name'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(db_index=True, max_length=100, verbose_name='Comercio de destino')),
                ('format', models.CharField(db_index=True, max_length=20, verbose_name='Formato consultado')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Momento del clic')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_clicks', to='books.book', verbose_name='Libro consultado')),
                ('buy_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='books.bookbuylink', verbose_name='Enlace pulsado')),
            ],
            options={
                'verbose_name': 'Clic de Marketplace',
                'verbose_name_plural': 'Clics de Marketplace',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Nombre de la editorial')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Identificador URL')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción o reseña histórica')),
                ('website', models.URLField(blank=True, default='', verbose_name='Sitio web oficial')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='publisher_logos/', verbose_name='Logotipo')),
                ('country', models.CharField(blank=True, default='España', max_length=100, verbose_name='País de origen')),
                ('is_verified', models.BooleanField(db_index=True, default=False, verbose_name='Editorial verificada')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_publishers', to=settings.AUTH_USER_MODEL, verbose_name='Usuario representante oficial')),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.publisher', verbose_name='Editorial'),
        ),
    ]
