# Generated by Django 5.2.17 on 2026-10-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0039_bookbuylink_marketplaceclick_publisher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, help_text='Número de páginas de la obra', null=True),
        ),
    ]
