# Generated by Django 5.2.17 on 2026-10-10 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0040_book_page_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='authorannouncement',
            name='is_moderated',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Censurado / Ocultado por moderación'),
        ),
        migrations.AddField(
            model_name='authorannouncement',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Publicación de pago'),
        ),
        migrations.AddField(
            model_name='authorannouncement',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de moderación'),
        ),
        migrations.AddField(
            model_name='authorannouncement',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_author_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Moderado por'),
        ),
        migrations.AddField(
            model_name='authorannouncement',
            name='moderation_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motivo de moderación'),
        ),
        migrations.AddField(
            model_name='authorannouncement',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Precio de acceso'),
        ),
    ]
