# Generated by Django 5.0 on 2025-10-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_is_private_user_birth_date_user_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_bio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_birth_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='show_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='show_location',
            field=models.BooleanField(default=True),
        ),
    ]
