# Generated by Django 5.0 on 2025-10-18 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_conversation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
