# Generated by Django 5.0 on 2025-11-28 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # Sustituye el 0004 duplicado de la otra rama si ya estaba aplicado.
    replaces = [
        ('users', '0004_user_blocked_users'),
    ]

    dependencies = [
        ('users', '0007_user_is_editor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
