# Generated by Django 5.2.17 on 2026-09-10 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_postgres_trigram_and_gin_indexes'),
        ('users', '0009_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BOOK_ADDED', 'Libro añadido'), ('BOOK_STARTED', 'Empezó a leer'), ('BOOK_FINISHED', 'Terminó de leer'), ('BOOK_RATED', 'Puntuó un libro'), ('REVIEW_CREATED', 'Publicó una reseña'), ('USER_FOLLOWED', 'Comenzó a seguir'), ('LIST_CREATED', 'Creó una lista')], db_index=True, max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='books.book')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='books.review')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_activity_user_created'), models.Index(fields=['-created_at'], name='idx_activity_created'), models.Index(fields=['type', '-created_at'], name='idx_activity_type_created')],
            },
        ),
    ]
