# Generated by Django 5.2.17 on 2026-09-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('FOLLOW', 'Nuevo seguidor'), ('MESSAGE', 'Nuevo mensaje'), ('REVIEW', 'Nueva reseña'), ('LIKE', 'Me gusta en reseña'), ('COMMENT', 'Comentario en reseña'), ('SYSTEM', 'Sistema')], default='SYSTEM', max_length=20),
        ),
    ]
