# Generated by Django 5.2.17 on 2026-09-12 11:00

import mybookconnect.media_security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Imagen de avatar (JPEG, PNG, WebP; máx 5MB; dimensiones 50x50 a 6000x6000px)', null=True, upload_to='avatars/', validators=[mybookconnect.media_security.AvatarImageValidator()]),
        ),
    ]
