# Generated by Django 5.2.17 on 2026-09-12 14:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0012_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Usuario'), ('EDITOR', 'Editor'), ('MODERATOR', 'Moderador'), ('ADMIN', 'Administrador')], db_index=True, default='USER', help_text='Jerarquía y rol del usuario (USER, EDITOR, MODERATOR, ADMIN)', max_length=20),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True, help_text='ID primario del objeto reportado')),
                ('reason', models.CharField(choices=[('SPAM', 'Spam o publicidad no deseada'), ('HARASSMENT', 'Acoso o intimidación'), ('HATE_SPEECH', 'Incitación al odio o violencia'), ('INAPPROPRIATE', 'Contenido explícito o inapropiado'), ('SPOILER', 'Spoilers sin advertencia'), ('COPYRIGHT', 'Infracción de derechos de autor'), ('OTHER', 'Otro motivo')], default='OTHER', help_text='Motivo de la denuncia', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Detalles adicionales proporcionados por el denunciante')),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('UNDER_REVIEW', 'En revisión'), ('RESOLVED', 'Resuelto'), ('REJECTED', 'Rechazado')], db_index=True, default='OPEN', help_text='Estado actual de la denuncia', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notas y justificación del moderador al resolver o rechazar')),
                ('action_taken', models.CharField(blank=True, help_text='Acción efectuada: HIDE_CONTENT, BAN_USER, DISMISS, WARNING', max_length=50)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(help_text='Modelo del objeto reportado', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(help_text='Usuario que realiza la denuncia', on_delete=django.db.models.deletion.CASCADE, related_name='filed_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Moderador o administrador que resolvió la denuncia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='idx_report_status_created'), models.Index(fields=['content_type', 'object_id'], name='idx_report_content_obj'), models.Index(fields=['reporter', 'status'], name='idx_report_reporter_status')],
            },
        ),
    ]
