# Generated by Django 5.2.17 on 2026-09-12 19:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0013_user_role_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ROLE_CHANGE', 'Cambio de Rol'), ('USER_BAN', 'Bloqueo de Usuario'), ('USER_UNBAN', 'Desbloqueo de Usuario'), ('USER_BLOCK', 'Bloqueo Social entre Usuarios'), ('USER_UNBLOCK', 'Desbloqueo Social entre Usuarios'), ('MODERATION_RESOLVE', 'Resolución de Denuncia'), ('MODERATION_REJECT', 'Rechazo de Denuncia'), ('CONTENT_DELETE', 'Eliminación de Contenido'), ('SECURITY_PASSWORD_CHANGE', 'Cambio de Contraseña'), ('OTHER', 'Otra Acción')], db_index=True, help_text='Identificador de la acción realizada', max_length=64)),
                ('object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('target_repr', models.CharField(blank=True, help_text='Representación textual congelada del objeto afectado', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP de origen', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User-Agent del cliente', max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información contextual estructurada adicional')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Marca temporal inmutable de la acción')),
                ('actor', models.ForeignKey(blank=True, help_text='Usuario que ejecutó la acción (o None para procesos del sistema)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='idx_audit_action_created'), models.Index(fields=['content_type', 'object_id'], name='idx_audit_content_obj'), models.Index(fields=['actor', '-created_at'], name='idx_audit_actor_created')],
            },
        ),
    ]
