# Generated by Django 5.2.17 on 2026-09-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Indica si la dirección de correo electrónico ha sido confirmada.'),
        ),
    ]
