# Generated by Django 5.2.17 on 2026-09-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gamification_enabled',
            field=models.BooleanField(default=True, help_text='Permite activar o desactivar opcionalmente la gamificación (retos, rachas, objetivos e insignias).'),
        ),
    ]
