# Generated by Django 5.2.17 on 2026-09-18 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_gamification_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='muted_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de finalización del silenciamiento disciplinario impuesto por moderación (Fase 58).', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='muted_users',
            field=models.ManyToManyField(blank=True, help_text='Usuarios silenciados socialmente por este usuario (Fase 58).', related_name='muted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ROLE_CHANGE', 'Cambio de Rol'), ('USER_BAN', 'Bloqueo de Usuario'), ('USER_UNBAN', 'Desbloqueo de Usuario'), ('USER_BLOCK', 'Bloqueo Social entre Usuarios'), ('USER_UNBLOCK', 'Desbloqueo Social entre Usuarios'), ('USER_MUTE', 'Silenciamiento Social entre Usuarios'), ('USER_UNMUTE', 'Des-silenciamiento Social entre Usuarios'), ('MODERATOR_MUTE', 'Silenciamiento Disciplinario de Usuario'), ('MODERATOR_UNMUTE', 'Levantamiento de Silenciamiento Disciplinario'), ('MODERATION_RESOLVE', 'Resolución de Denuncia'), ('MODERATION_REJECT', 'Rechazo de Denuncia'), ('CONTENT_HIDE', 'Ocultación de Contenido'), ('CONTENT_RESTORE', 'Restauración de Contenido'), ('CONTENT_DELETE', 'Eliminación de Contenido'), ('SECURITY_PASSWORD_CHANGE', 'Cambio de Contraseña'), ('OTHER', 'Otra Acción')], db_index=True, help_text='Identificador de la acción realizada', max_length=64),
        ),
    ]
