# Generated by Django 5.2.17 on 2026-09-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_muted_until_user_muted_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_privacy_level',
            field=models.CharField(choices=[('public', 'Público'), ('friends', 'Solo amigos'), ('private', 'Privado')], db_index=True, default='public', help_text='Nivel de privacidad específico para el feed de actividad y eventos sociales.', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='allow_messages_from',
            field=models.CharField(choices=[('everyone', 'Todos los usuarios'), ('followed', 'Solo personas que sigo / amigos'), ('nobody', 'Nadie')], db_index=True, default='everyone', help_text='Control de recepción de mensajes directos.', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='reading_privacy_level',
            field=models.CharField(choices=[('public', 'Público'), ('friends', 'Solo amigos'), ('private', 'Privado')], db_index=True, default='public', help_text='Nivel de privacidad específico para la biblioteca y lecturas.', max_length=10),
        ),
    ]
