# Generated by Django 5.2.17 on 2026-09-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_activity_privacy_level_user_allow_messages_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allow_messages_from',
            field=models.CharField(choices=[('everyone', 'Todos los usuarios'), ('followed', 'Solo personas que sigo / amigos'), ('nobody', 'Nadie')], db_index=True, default='followed', help_text='Control de recepción de mensajes directos.', max_length=10),
        ),
    ]
