# Generated by Django 5.2.17 on 2026-09-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_allow_messages_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('SPAM', 'Spam o publicidad no deseada'), ('HARASSMENT', 'Acoso o intimidación'), ('HATE_SPEECH', 'Incitación al odio o violencia'), ('INAPPROPRIATE', 'Contenido explícito o inapropiado'), ('SPOILER', 'Spoilers sin advertencia'), ('COPYRIGHT', 'Infracción de derechos de autor'), ('ILLEGAL_CONTENT', 'Contenido ilegal o perjudicial'), ('IMPERSONATION', 'Suplantación de identidad o engaño'), ('OTHER', 'Otro motivo')], default='OTHER', help_text='Motivo de la denuncia', max_length=30),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Abierto'), ('UNDER_REVIEW', 'En revisión'), ('INVESTIGATING', 'En investigación'), ('RESOLVED', 'Resuelto'), ('REJECTED', 'Rechazado'), ('DISMISSED', 'Desestimado')], db_index=True, default='OPEN', help_text='Estado actual de la denuncia', max_length=20),
        ),
    ]
