# Generated by Django 5.2.17 on 2026-09-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_report_reason_alter_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Fecha de eliminación y anonimización de la cuenta por solicitud del usuario (Fase 17 - RGPD).', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de consentimiento y aceptación de la Política de Privacidad.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de consentimiento y aceptación de los Términos de Servicio.', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ROLE_CHANGE', 'Cambio de Rol'), ('USER_BAN', 'Bloqueo de Usuario'), ('USER_UNBAN', 'Desbloqueo de Usuario'), ('USER_BLOCK', 'Bloqueo Social entre Usuarios'), ('USER_UNBLOCK', 'Desbloqueo Social entre Usuarios'), ('USER_MUTE', 'Silenciamiento Social entre Usuarios'), ('USER_UNMUTE', 'Des-silenciamiento Social entre Usuarios'), ('MODERATOR_MUTE', 'Silenciamiento Disciplinario de Usuario'), ('MODERATOR_UNMUTE', 'Levantamiento de Silenciamiento Disciplinario'), ('MODERATION_RESOLVE', 'Resolución de Denuncia'), ('MODERATION_REJECT', 'Rechazo de Denuncia'), ('CONTENT_HIDE', 'Ocultación de Contenido'), ('CONTENT_RESTORE', 'Restauración de Contenido'), ('CONTENT_DELETE', 'Eliminación de Contenido'), ('SECURITY_PASSWORD_CHANGE', 'Cambio de Contraseña'), ('USER_DELETE', 'Eliminación y Anonimización de Cuenta'), ('EMAIL_CHANGE', 'Cambio de Dirección de Correo Electrónico'), ('DATA_EXPORT', 'Exportación de Datos Personales (GDPR)'), ('OTHER', 'Otra Acción')], db_index=True, help_text='Identificador de la acción realizada', max_length=64),
        ),
    ]
