# Generated by Django 5.2.17 on 2026-09-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_alter_legaldocument_slug'),
        ('users', '0021_user_deleted_at_user_privacy_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_categories',
            field=models.ManyToManyField(blank=True, help_text='Categorías o géneros literarios favoritos seleccionados por el lector durante el onboarding.', related_name='favorited_by_users', to='books.category'),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica si el usuario ha completado o desestimado el flujo de bienvenida/onboarding (Fase 19).'),
        ),
    ]
