# Generated by Django 5.2.17 on 2026-09-27 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_favorite_categories_user_onboarding_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('BOOK_ADDED', 'Libro añadido'), ('BOOK_STARTED', 'Empezó a leer'), ('BOOK_FINISHED', 'Terminó de leer'), ('BOOK_RATED', 'Puntuó un libro'), ('REVIEW_CREATED', 'Publicó una reseña'), ('USER_FOLLOWED', 'Comenzó a seguir'), ('LIST_CREATED', 'Creó una lista'), ('REVIEW_LIKED', 'Le gustó una reseña'), ('COMMENT_ADDED', 'Comentó en una reseña')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='HiddenActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by_users', to='users.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_feed_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'activity'], name='idx_hidden_user_activity')],
                'unique_together': {('user', 'activity')},
            },
        ),
    ]
