# Generated by Django 5.2.17 on 2026-09-27 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_add_hidden_activity_and_activity_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('FOLLOW', 'Nuevo seguidor'), ('FOLLOW_ACCEPTED', 'Solicitud de seguimiento aceptada'), ('MESSAGE', 'Nuevo mensaje'), ('REVIEW', 'Nueva reseña'), ('LIKE', 'Me gusta en reseña'), ('COMMENT', 'Comentario'), ('REPLY', 'Respuesta a comentario'), ('LIST_FOLLOW', 'Interacción en lista social'), ('RECOMMENDATION', 'Nueva recomendación'), ('SYSTEM', 'Sistema')], default='SYSTEM', max_length=20),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app_follow', models.BooleanField(default=True)),
                ('in_app_follow_accepted', models.BooleanField(default=True)),
                ('in_app_like', models.BooleanField(default=True)),
                ('in_app_comment', models.BooleanField(default=True)),
                ('in_app_reply', models.BooleanField(default=True)),
                ('in_app_list', models.BooleanField(default=True)),
                ('in_app_message', models.BooleanField(default=True)),
                ('in_app_recommendation', models.BooleanField(default=True)),
                ('email_follow', models.BooleanField(default=False)),
                ('email_follow_accepted', models.BooleanField(default=False)),
                ('email_like', models.BooleanField(default=False)),
                ('email_comment', models.BooleanField(default=True)),
                ('email_reply', models.BooleanField(default=True)),
                ('email_list', models.BooleanField(default=False)),
                ('email_message', models.BooleanField(default=True)),
                ('email_recommendation', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
