# Generated by Django 5.2.17 on 2026-09-29 17:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_notification_type_notificationpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Gratuito'), ('premium', 'Premium / Mecenas')], db_index=True, default='free', max_length=20, verbose_name='Nivel de suscripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Suscripción de Usuario',
                'verbose_name_plural': 'Suscripciones de Usuarios',
            },
        ),
    ]
