# Generated by Django 5.2.17 on 2026-09-29 17:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0029_book_authors'),
        ('users', '0025_usersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('BOOK_ADDED', 'Libro añadido'), ('BOOK_STARTED', 'Empezó a leer'), ('BOOK_FINISHED', 'Terminó de leer'), ('BOOK_RATED', 'Puntuó un libro'), ('REVIEW_CREATED', 'Publicó una reseña'), ('USER_FOLLOWED', 'Comenzó a seguir'), ('LIST_CREATED', 'Creó una lista'), ('REVIEW_LIKED', 'Le gustó una reseña'), ('COMMENT_ADDED', 'Comentó en una reseña'), ('POST_CREATED', 'Publicó en el muro')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Contenido de la publicación en el muro (máx 2000 caracteres)')),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wall_posts_authored', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wall_posts', to='books.book')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wall_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.userpost'),
        ),
        migrations.CreateModel(
            name='UserPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.userpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='users.userpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='userpost',
            index=models.Index(fields=['target_user', '-created_at'], name='idx_post_target_created'),
        ),
        migrations.AddIndex(
            model_name='userpost',
            index=models.Index(fields=['author', '-created_at'], name='idx_post_author_created'),
        ),
        migrations.AddIndex(
            model_name='userpostcomment',
            index=models.Index(fields=['post', 'created_at'], name='idx_post_comment_created'),
        ),
        migrations.AddIndex(
            model_name='userpostlike',
            index=models.Index(fields=['post', 'user'], name='idx_post_like_user'),
        ),
        migrations.AddConstraint(
            model_name='userpostlike',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_user_post_like'),
        ),
    ]
