# Generated by Django 5.2.17 on 2026-10-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_activity_type_userpost_activity_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('reader', 'Lector'), ('author', 'Escritor / Autor'), ('both', 'Lector y Escritor')], db_index=True, default='reader', help_text='Modalidad de cuenta en la plataforma: lector, escritor/autor o ambos.', max_length=20),
        ),
    ]
